### PR TITLE
Lola Heffernan [Intro-Python-II]

### PR DESCRIPTION
**Pull request by lolax**

### CODE REVIEW

**Comment by lolax** [comment]
@brianaruff I believe I've reached MVP, but I know I went about it a bit differently than the instructions. Firstly, in order to make the movement options more dynamic, I made the room association dict have keys for each room with values that are a list of dicts with each available direction & destination. I tried to make the movement options dynamic without changing the room association structure, but I could not reason about it without nested formatted strings (which don't work). Also, instead of giving the Item class on_take and on_drop methods, I gave methods for passing items to the Room and Player classes. Let me know if you'd like me to change it so that the methods are part of the Item class. 🌵

**Comment by BrianARuff** [comment]
Excellent job, once again I am impressed! I can tell you have some RP experience or at least have played some RP games, but correct me if I am wrong!

I did a `git checkout lola` and ran the adventure and I was able to fully play the game which I enjoyed. There are somethings I think you can think about adding though. When I got to the treasure room it said the chest was empty but there were some items in the room which is fine as that is what they put in there, but there were multiple items. I am wondering if you could implement a way to parse input to pick up multiple items. For example, `take bottle robe` and then it picks up both items. It's deff. not a requirement but it should get your brain thinking about how to work with and parse input using argv plus I'll be curious to know what you come up with!

**Comment by BrianARuff** [comment]
I have no problem with the way u implemented picking up and dropping items. I think your way it just as intuitive as the way they had it.

**Review by BrianARuff — APPROVED** [review]
Great job with your MVP and starting on NPCs.

**Pull request merged**
